stages:
  - build

build-release:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.21.0-debug
    entrypoint: ['']
  script:
    - export VERSION="v$(cat package.json | grep version | head -1 | awk -F':' '{ print $2 }' | sed 's/[\",]//g' | cut -c2-)"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${VERSION}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --target production
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:migration-${VERSION}"
      --destination "${CI_REGISTRY_IMAGE}:migration-latest"
      --target migration
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:seed-${VERSION}"
      --destination "${CI_REGISTRY_IMAGE}:seed-latest"
      --target seed
  rules:
    - if: $CI_COMMIT_TAG

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.21.0-debug
    entrypoint: ['']
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:migration-${CI_COMMIT_SHORT_SHA}"
      --target migration
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:seed-${CI_COMMIT_SHORT_SHA}"
      --target seed
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
