stages:
- build

build-release:
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: [""]
  script:
    - echo "$DOCKER_AUTH" > /kaniko/.docker/config.json
    - export VERSION="v$(cat package.json | grep version | head -1 | awk -F':' '{ print $2 }' | sed 's/[\",]//g' | cut -c2-)"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "registry.supporterino.de/yarm/backend:${VERSION}"
      --destination "registry.supporterino.de/yarm/backend:latest"
  rules:
    - if: $CI_COMMIT_TAG

build:
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: [""]
  script:
    - echo "$DOCKER_AUTH" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "registry.supporterino.de/yarm/backend:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
