apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yarm.fullname" . }}
  labels: {{ include "yarm.labels" . | nindent 4 }}
data:
    {{- $defaultEnv := .Files.Get "environment/environment.yaml" | fromYaml  }}
    {{- $env := merge $defaultEnv .Values.env }}
    {{- range $key, $value := $env }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}